#! /bin/sh

xsetroot -cursor_name left_ptr

### bspwm options
bspc monitor -d '1' '2' '3' '4' '5' #'6'
bspc config border_width 2
bspc config window_gap 1
bspc config top_padding 25
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config split_ratio 0.50
bspc config borderless_monocle false
bspc config gapless_monocle true
bspc config single_monocle true
bspc config focus_follows_pointer false
bspc config normal_border_color '#363636'
bspc config active_border_color '#FFFFFF'
bspc config focused_border_color '#C6772A'
bspc config presel_feedback_color '#363636'
bspc config pointer_modifier mod4
bspc config pointer_action1 resize_corner
bspc config pointer_action2 resize_side
bspc config pointer_action3 move
bspc config external_rules_command ~/.config/bspwm/aux/external-rules

### autostart
sxhkd &
picom -b --no-fading-openclose
# while in desktop 1, spawn windows in floating state
bspc subscribe node_add | while read event monitor_id desktop_id ip_id node_id; do
  [ "$(bspc query -D -d '^1')" = $desktop_id ] && bspc node -t floating
done &

### Rules
bspc rule -a "Gimp-2.10" state=floating
bspc rule -a "Emoji-keyboard" state=floating rectangle=770x242+330+355
bspc rule -a "Xfce4-appfinder" state=floating rectangle=626x504+0+0 center=true

